package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/neirth/openlobster/internal/application/graphql/generated"
	"github.com/neirth/openlobster/internal/application/graphql/resolvers/mappers"
)

// SpawnSubAgent is the resolver for the spawnSubAgent field.
func (r *mutationResolver) SpawnSubAgent(ctx context.Context, name string, model string, task *string) (*generated.SpawnSubAgentResult, error) {
	if r.Deps == nil {
		return &generated.SpawnSubAgentResult{Success: true}, nil
	}
	taskVal := ""
	if task != nil {
		taskVal = *task
	}
	id, err := r.Deps.SpawnSubAgent(ctx, name, model, taskVal)
	if err != nil {
		return nil, err
	}
	if id == "" {
		return &generated.SpawnSubAgentResult{Success: true}, nil
	}
	return &generated.SpawnSubAgentResult{Success: true, ID: &id}, nil
}

// KillSubAgent is the resolver for the killSubAgent field.
func (r *mutationResolver) KillSubAgent(ctx context.Context, id string) (*generated.KillSubAgentResult, error) {
	if r.Deps == nil {
		return &generated.KillSubAgentResult{Success: true}, nil
	}
	if err := r.Deps.KillSubAgent(ctx, id); err != nil {
		return nil, err
	}
	return &generated.KillSubAgentResult{Success: true}, nil
}

// Agent is the resolver for the agent field.
func (r *queryResolver) Agent(ctx context.Context) (*generated.Agent, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return mappers.SnapshotToAgent(r.Deps.Agent(ctx)), nil
}

// Channels is the resolver for the channels field.
func (r *queryResolver) Channels(ctx context.Context) ([]*generated.Channel, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return mappers.ChannelsToGenerated(r.Deps.Channels(ctx)), nil
}

// Heartbeat is the resolver for the heartbeat field.
func (r *queryResolver) Heartbeat(ctx context.Context) (*generated.Heartbeat, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return mappers.HeartbeatToGenerated(r.Deps.Heartbeat(ctx)), nil
}

// Tools is the resolver for the tools field.
func (r *queryResolver) Tools(ctx context.Context) ([]*generated.Tool, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return mappers.ToolsToGenerated(r.Deps.MCPTools(ctx)), nil
}

// SubAgents is the resolver for the subAgents field.
func (r *queryResolver) SubAgents(ctx context.Context) ([]*generated.SubAgent, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return mappers.SubAgentsToGenerated(r.Deps.SubAgents(ctx)), nil
}

// Status is the resolver for the status field.
func (r *queryResolver) Status(ctx context.Context) (*generated.Status, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return mappers.StatusToGenerated(r.Deps.Status(ctx)), nil
}

// Metrics is the resolver for the metrics field.
func (r *queryResolver) Metrics(ctx context.Context) (*generated.Metrics, error) {
	if r.Deps == nil {
		return nil, nil
	}
	snap := r.Deps.Metrics(ctx)
	if snap == nil {
		return nil, fmt.Errorf("metrics unavailable")
	}
	return mappers.MetricsToGenerated(snap), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
