package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/neirth/openlobster/internal/application/graphql/generated"
	"github.com/neirth/openlobster/internal/application/graphql/resolvers/mappers"
)

// UpdateConfig is the resolver for the updateConfig field.
func (r *mutationResolver) UpdateConfig(ctx context.Context, input generated.UpdateConfigInput) (*generated.UpdateConfigResult, error) {
	if r.Deps == nil {
		return &generated.UpdateConfigResult{}, nil
	}
	m := mappers.UpdateConfigInputToMap(input)
	if err := r.Deps.UpdateConfig(ctx, m); err != nil {
		return nil, err
	}
	return mappers.AppConfigSnapshotToUpdateConfigResult(r.Deps.Config(ctx)), nil
}

// Config is the resolver for the config field.
func (r *queryResolver) Config(ctx context.Context) (*generated.AppConfig, error) {
	if r.Deps == nil {
		return &generated.AppConfig{}, nil
	}
	return mappers.AppConfigSnapshotToGenerated(r.Deps.Config(ctx)), nil
}
