package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/neirth/openlobster/internal/application/graphql/generated"
	"github.com/neirth/openlobster/internal/application/graphql/resolvers/mappers"
	"github.com/neirth/openlobster/internal/domain/handlers"
	"github.com/neirth/openlobster/internal/domain/models"
)

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, conversationID string) (*generated.MutationResult, error) {
	if r.Deps == nil {
		return &generated.MutationResult{Success: true}, nil
	}
	if err := r.Deps.DeleteUser(ctx, conversationID); err != nil {
		return nil, err
	}
	return &generated.MutationResult{Success: true}, nil
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, conversationID *string, channelID *string, content string) (*generated.MessageSentResult, error) {
	if r.Deps == nil {
		return nil, fmt.Errorf("sendMessage: deps not configured")
	}
	cid := ""
	if conversationID != nil {
		cid = *conversationID
	}
	if cid == "" && channelID != nil {
		cid = *channelID
	}
	if cid == "" {
		return nil, fmt.Errorf("sendMessage: conversationID or channelID required")
	}
	// If a MessageDispatcher is available, use unified handler and include
	// optional attachments passed as a JSON string in the GraphQL variables
	// (frontend declares `$attachments: String` and sends JSON there).
	if r.Deps.MessageDispatcher != nil {
		// Try to read attachments raw JSON from operation variables.
		op := graphql.GetOperationContext(ctx)
		var atts []models.Attachment
		if op != nil {
			if v, ok := op.Variables["attachments"]; ok && v != nil {
				// v may be a JSON string or an already-parsed structure. Marshal
				// it back to JSON bytes and unmarshal into the domain struct so
				// that JSON tags (e.g. "mime_type") are respected.
				var raw []byte
				switch vv := v.(type) {
				case string:
					if vv != "" {
						raw = []byte(vv)
					}
				default:
					if b, err := json.Marshal(vv); err == nil {
						raw = b
					}
				}
				if len(raw) > 0 {
					var parsed []models.Attachment
					if err := json.Unmarshal(raw, &parsed); err == nil {
						atts = parsed
					}
				}
			}
		}

		if err := r.Deps.MessageDispatcher.Handle(ctx, handlers.HandleMessageInput{
			ChannelID:      cid,
			Content:        content,
			ChannelType:    "dashboard",
			ConversationID: &cid,
			SenderID:       "dashboard",
			SenderName:     "Dashboard",
			Attachments:    atts,
		}); err != nil {
			return nil, err
		}
		ok := true
		return &generated.MessageSentResult{Success: &ok}, nil
	}

	// Fallback: use existing deps.SendMessage behaviour when dispatcher not wired
	res, err := r.Deps.SendMessage(ctx, cid, content)
	if err != nil {
		return nil, err
	}
	if res == nil {
		ok := true
		return &generated.MessageSentResult{Success: &ok}, nil
	}
	return mappers.SendMessageResultToGenerated(res), nil
}

// Conversations is the resolver for the conversations field.
func (r *queryResolver) Conversations(ctx context.Context) ([]*generated.Conversation, error) {
	if r.Deps == nil {
		return nil, nil
	}
	list, err := r.Deps.Conversations(ctx)
	if err != nil {
		return nil, err
	}
	return mappers.ConversationsToGenerated(list), nil
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, conversationID string, before *string, limit *int) ([]*generated.Message, error) {
	if r.Deps == nil {
		return nil, nil
	}
	list, err := r.Deps.Messages(ctx, conversationID, before, limit)
	if err != nil {
		return nil, err
	}
	return mappers.MessagesToGenerated(list), nil
}
