package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/neirth/openlobster/internal/application/graphql/generated"
	"github.com/neirth/openlobster/internal/application/graphql/resolvers/mappers"
)

// ConnectMcp is the resolver for the connectMcp field.
func (r *mutationResolver) ConnectMcp(ctx context.Context, name string, transport *string, url *string) (*generated.MCPConnectResult, error) {
	if r.Deps == nil {
		return &generated.MCPConnectResult{}, nil
	}
	tr, u := "", ""
	if transport != nil {
		tr = *transport
	}
	if url != nil {
		u = *url
	}
	reqAuth, err := r.Deps.ConnectMCP(ctx, name, tr, u)
	if err != nil {
		// When the server requires OAuth (401/unauthorized), return success with
		// requiresAuth so the frontend can launch the OAuth flow instead of showing an error.
		if reqAuth {
			success := false
			return &generated.MCPConnectResult{Success: &success, RequiresAuth: &reqAuth}, nil
		}
		return nil, err
	}
	success := true
	return &generated.MCPConnectResult{Success: &success, RequiresAuth: &reqAuth}, nil
}

// DisconnectMcp is the resolver for the disconnectMcp field.
func (r *mutationResolver) DisconnectMcp(ctx context.Context, name string) (bool, error) {
	if r.Deps == nil {
		return true, nil
	}
	if err := r.Deps.DisconnectMCP(ctx, name); err != nil {
		return false, err
	}
	return true, nil
}

// InitiateOAuth is the resolver for the initiateOAuth field.
func (r *mutationResolver) InitiateOAuth(ctx context.Context, name string, url string) (*generated.OAuthInitiateResult, error) {
	if r.Deps == nil {
		return nil, nil
	}
	authURL, err := r.Deps.InitiateOAuth(ctx, name, url)
	if err != nil {
		return nil, err
	}
	return &generated.OAuthInitiateResult{Success: true, AuthURL: &authURL}, nil
}

// Mcps is the resolver for the mcps field.
func (r *queryResolver) Mcps(ctx context.Context) ([]*generated.Mcp, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return mappers.MCPsToGenerated(r.Deps.MCPs(ctx)), nil
}

// McpServers is the resolver for the mcpServers field.
func (r *queryResolver) McpServers(ctx context.Context) ([]*generated.MCPServer, error) {
	if r.Deps == nil {
		return nil, nil
	}
	list, err := r.Deps.MCPServers(ctx)
	if err != nil {
		return nil, err
	}
	return mappers.MCPServersToGenerated(list), nil
}

// McpTools is the resolver for the mcpTools field.
func (r *queryResolver) McpTools(ctx context.Context) ([]*generated.MCPTool, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return mappers.MCPToolsToGenerated(r.Deps.MCPTools(ctx)), nil
}

// McpOAuthStatus is the resolver for the mcpOAuthStatus field.
func (r *queryResolver) McpOAuthStatus(ctx context.Context, name string) (*generated.MCPOAuthStatus, error) {
	if r.Deps == nil {
		return &generated.MCPOAuthStatus{Status: "unknown"}, nil
	}
	status, err := r.Deps.MCPOAuthStatus(ctx, name)
	if err != nil {
		return nil, err
	}
	return &generated.MCPOAuthStatus{Status: status}, nil
}
