package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/google/uuid"
	"github.com/neirth/openlobster/internal/application/graphql/generated"
	"github.com/neirth/openlobster/internal/application/graphql/resolvers/mappers"
	"github.com/neirth/openlobster/internal/application/graphql/resolvers/utils"
)

// AddMemory is the resolver for the addMemory field.
func (r *mutationResolver) AddMemory(ctx context.Context, content string) (*generated.MutationResult, error) {
	if r.Deps == nil {
		return &generated.MutationResult{Success: true}, nil
	}
	err := r.Deps.AddMemory(ctx, "dashboard", content)
	result := &generated.MutationResult{Success: err == nil}
	if err != nil {
		errStr := err.Error()
		result.Error = &errStr
	}
	return result, nil
}

// AddMemoryNode is the resolver for the addMemoryNode field.
func (r *mutationResolver) AddMemoryNode(ctx context.Context, label string, typeArg string, value string) (*generated.MemoryNode, error) {
	if r.Deps == nil {
		return nil, nil
	}
	id, err := r.Deps.AddMemoryNode(ctx, label, typeArg, value)
	if err != nil {
		return nil, err
	}
	if id == "" {
		id = uuid.New().String()
	}
	return &generated.MemoryNode{
		ID:    id,
		Label: &label,
		Type:  &typeArg,
		Value: &value,
	}, nil
}

// UpdateMemoryNode is the resolver for the updateMemoryNode field.
func (r *mutationResolver) UpdateMemoryNode(ctx context.Context, id string, label *string, typeArg *string, value *string, properties *string) (*generated.MemoryNode, error) {
	if r.Deps == nil {
		return nil, nil
	}
	lbl, typ, val := utils.PtrStr(label), utils.PtrStr(typeArg), utils.PtrStr(value)
	props := utils.ParseProperties(properties)
	if err := r.Deps.UpdateMemoryNode(ctx, id, lbl, typ, val, props); err != nil {
		return nil, err
	}
	return &generated.MemoryNode{
		ID:         id,
		Label:      label,
		Type:       typeArg,
		Value:      value,
		Properties: utils.PropsToAny(props),
	}, nil
}

// DeleteMemoryNode is the resolver for the deleteMemoryNode field.
func (r *mutationResolver) DeleteMemoryNode(ctx context.Context, id string) (bool, error) {
	if r.Deps == nil {
		return true, nil
	}
	err := r.Deps.DeleteMemoryNode(ctx, id)
	return err == nil, err
}

// AddRelation is the resolver for the addRelation field.
func (r *mutationResolver) AddRelation(ctx context.Context, from string, to string, relationType string) (*generated.AddRelationResult, error) {
	if r.Deps == nil {
		return &generated.AddRelationResult{Success: true}, nil
	}
	err := r.Deps.AddRelation(ctx, from, to, relationType)
	result := &generated.AddRelationResult{Success: err == nil}
	if err != nil {
		errStr := err.Error()
		result.Error = &errStr
	}
	return result, nil
}

// ExecuteCypher is the resolver for the executeCypher field.
func (r *mutationResolver) ExecuteCypher(ctx context.Context, cypher string) (*generated.CypherResult, error) {
	if r.Deps == nil {
		return &generated.CypherResult{Success: true}, nil
	}
	_, err := r.Deps.ExecuteCypher(ctx, cypher)
	result := &generated.CypherResult{Success: err == nil}
	if err != nil {
		errStr := err.Error()
		result.Error = &errStr
	}
	return result, nil
}

// SearchMemory is the resolver for the searchMemory field.
func (r *queryResolver) SearchMemory(ctx context.Context, query string) (*generated.SearchMemoryResult, error) {
	if r.Deps == nil {
		return &generated.SearchMemoryResult{Success: true, Result: utils.StringPtr("")}, nil
	}
	result, err := r.Deps.SearchMemory(ctx, "", query)
	res := &generated.SearchMemoryResult{Success: err == nil, Result: &result}
	if err != nil {
		errStr := err.Error()
		res.Error = &errStr
	}
	return res, nil
}

// UserGraph is the resolver for the userGraph field.
func (r *queryResolver) UserGraph(ctx context.Context, userID *string) (*generated.UserGraphResult, error) {
	if r.Deps == nil {
		return &generated.UserGraphResult{Success: true, Nodes: []*generated.GraphNode{}, Edges: []*generated.GraphEdge{}}, nil
	}
	uid := ""
	if userID != nil {
		uid = *userID
	}
	snap, err := r.Deps.UserGraph(ctx, uid)
	if err != nil {
		errStr := err.Error()
		return &generated.UserGraphResult{Success: false, Error: &errStr}, nil
	}
	if snap == nil {
		return &generated.UserGraphResult{Success: true, Nodes: []*generated.GraphNode{}, Edges: []*generated.GraphEdge{}}, nil
	}
	return &generated.UserGraphResult{
		Success: true,
		Nodes:   mappers.GraphNodesToGenerated(snap.Nodes),
		Edges:   mappers.GraphEdgesToGenerated(snap.Edges),
	}, nil
}

// Memory is the resolver for the memory field.
func (r *queryResolver) Memory(ctx context.Context) (*generated.MemoryGraph, error) {
	if r.Deps == nil {
		return &generated.MemoryGraph{Nodes: []*generated.MemoryNode{}, Edges: []*generated.MemoryEdge{}}, nil
	}
	snap, err := r.Deps.MemoryGraph(ctx)
	if err != nil {
		return nil, err
	}
	if snap == nil {
		return &generated.MemoryGraph{Nodes: []*generated.MemoryNode{}, Edges: []*generated.MemoryEdge{}}, nil
	}
	return &generated.MemoryGraph{
		Nodes: mappers.MemoryNodesFromSnapshot(snap.Nodes),
		Edges: mappers.MemoryEdgesFromSnapshot(snap.Edges),
	}, nil
}
