package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/neirth/openlobster/internal/application/graphql/generated"
	"github.com/neirth/openlobster/internal/application/graphql/resolvers/mappers"
)

// EnableSkill is the resolver for the enableSkill field.
func (r *mutationResolver) EnableSkill(ctx context.Context, name string) (bool, error) {
	if r.Deps == nil {
		return false, nil
	}
	if err := r.Deps.EnableSkill(ctx, name); err != nil {
		return false, err
	}
	return true, nil
}

// DisableSkill is the resolver for the disableSkill field.
func (r *mutationResolver) DisableSkill(ctx context.Context, name string) (bool, error) {
	if r.Deps == nil {
		return false, nil
	}
	if err := r.Deps.DisableSkill(ctx, name); err != nil {
		return false, err
	}
	return true, nil
}

// DeleteSkill is the resolver for the deleteSkill field.
func (r *mutationResolver) DeleteSkill(ctx context.Context, name string) (bool, error) {
	if r.Deps == nil {
		return false, nil
	}
	if err := r.Deps.DeleteSkill(ctx, name); err != nil {
		return false, err
	}
	return true, nil
}

// ImportSkill is the resolver for the importSkill field.
// The frontend sends the .skill archive as base64; we decode before passing to the adapter.
func (r *mutationResolver) ImportSkill(ctx context.Context, data string) (*generated.ImportSkillResult, error) {
	if r.Deps == nil {
		return &generated.ImportSkillResult{Success: true}, nil
	}
	// Trim whitespace/newlines that some clients may add to long strings
	data = strings.TrimSpace(data)
	decoded, err := base64.StdEncoding.DecodeString(data)
	if err != nil {
		// Try base64.RawStdEncoding (no padding) as fallback
		decoded, err = base64.RawStdEncoding.DecodeString(data)
	}
	if err != nil {
		errStr := "invalid base64 data: " + err.Error()
		return &generated.ImportSkillResult{Success: false, Error: &errStr}, nil
	}
	if err := r.Deps.ImportSkill(ctx, decoded); err != nil {
		errStr := err.Error()
		return &generated.ImportSkillResult{Success: false, Error: &errStr}, nil
	}
	return &generated.ImportSkillResult{Success: true}, nil
}

// WriteSystemFile is the resolver for the writeSystemFile field.
func (r *mutationResolver) WriteSystemFile(ctx context.Context, name string, content string) (*generated.MutationResult, error) {
	if r.Deps == nil {
		return nil, fmt.Errorf("writeSystemFile: deps not configured")
	}
	if err := r.Deps.WriteSystemFile(ctx, name, content); err != nil {
		errStr := err.Error()
		return &generated.MutationResult{Success: false, Error: &errStr}, nil
	}
	return &generated.MutationResult{Success: true}, nil
}

// Skills is the resolver for the skills field.
func (r *queryResolver) Skills(ctx context.Context) ([]*generated.Skill, error) {
	if r.Deps == nil {
		return nil, nil
	}
	list, err := r.Deps.Skills(ctx)
	if err != nil {
		return nil, err
	}
	return mappers.SkillsToGenerated(list), nil
}

// SystemFiles is the resolver for the systemFiles field.
func (r *queryResolver) SystemFiles(ctx context.Context) ([]*generated.SystemFile, error) {
	if r.Deps == nil {
		return nil, nil
	}
	list, err := r.Deps.SystemFiles(ctx)
	if err != nil {
		return nil, err
	}
	return mappers.SystemFilesToGenerated(list), nil
}
