package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/neirth/openlobster/internal/application/graphql/generated"
	"github.com/neirth/openlobster/internal/domain/events"
)

// Events is the resolver for the events field.
func (r *subscriptionResolver) Events(ctx context.Context, eventType *string) (<-chan *generated.EventPayload, error) {
	if eventType == nil || *eventType == "" {
		return r.subscribeAll(ctx)
	}
	return r.subscribe(ctx, *eventType)
}

// OnMessageReceived is the resolver for the onMessageReceived field.
func (r *subscriptionResolver) OnMessageReceived(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventMessageReceived)
}

// OnMessageSent is the resolver for the onMessageSent field.
func (r *subscriptionResolver) OnMessageSent(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventMessageSent)
}

// OnMessageProcessed is the resolver for the onMessageProcessed field.
func (r *subscriptionResolver) OnMessageProcessed(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventMessageProcessed)
}

// OnSessionStarted is the resolver for the onSessionStarted field.
func (r *subscriptionResolver) OnSessionStarted(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventSessionStarted)
}

// OnSessionEnded is the resolver for the onSessionEnded field.
func (r *subscriptionResolver) OnSessionEnded(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventSessionEnded)
}

// OnUserPaired is the resolver for the onUserPaired field.
func (r *subscriptionResolver) OnUserPaired(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventUserPaired)
}

// OnUserUnpaired is the resolver for the onUserUnpaired field.
func (r *subscriptionResolver) OnUserUnpaired(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventUserUnpaired)
}

// OnPairingRequested is the resolver for the onPairingRequested field.
func (r *subscriptionResolver) OnPairingRequested(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventPairingRequested)
}

// OnPairingApproved is the resolver for the onPairingApproved field.
func (r *subscriptionResolver) OnPairingApproved(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventPairingApproved)
}

// OnPairingDenied is the resolver for the onPairingDenied field.
func (r *subscriptionResolver) OnPairingDenied(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventPairingDenied)
}

// OnTaskAdded is the resolver for the onTaskAdded field.
func (r *subscriptionResolver) OnTaskAdded(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventTaskAdded)
}

// OnTaskCompleted is the resolver for the onTaskCompleted field.
func (r *subscriptionResolver) OnTaskCompleted(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventTaskCompleted)
}

// OnCronJobExecuted is the resolver for the onCronJobExecuted field.
func (r *subscriptionResolver) OnCronJobExecuted(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventCronJobExecuted)
}

// OnMCPServerConnected is the resolver for the onMCPServerConnected field.
func (r *subscriptionResolver) OnMCPServerConnected(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventMCPServerConnected)
}

// OnMCPServerDisconnected is the resolver for the onMCPServerDisconnected field.
func (r *subscriptionResolver) OnMCPServerDisconnected(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventMCPServerDisconnected)
}

// OnMemoryUpdated is the resolver for the onMemoryUpdated field.
func (r *subscriptionResolver) OnMemoryUpdated(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventMemoryUpdated)
}

// OnCompactionTriggered is the resolver for the onCompactionTriggered field.
func (r *subscriptionResolver) OnCompactionTriggered(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventCompactionTriggered)
}

// OnCompactionCompleted is the resolver for the onCompactionCompleted field.
func (r *subscriptionResolver) OnCompactionCompleted(ctx context.Context) (<-chan *generated.EventPayload, error) {
	return r.subscribe(ctx, events.EventCompactionCompleted)
}

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
