package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/neirth/openlobster/internal/application/graphql/generated"
	"github.com/neirth/openlobster/internal/application/graphql/resolvers/mappers"
	"github.com/neirth/openlobster/internal/application/graphql/resolvers/utils"
)

// SetToolPermission is the resolver for the setToolPermission field.
func (r *mutationResolver) SetToolPermission(ctx context.Context, userID string, toolName string, mode string) (*generated.MutationResult, error) {
	if r.Deps == nil {
		return &generated.MutationResult{Success: true}, nil
	}
	if err := r.Deps.SetToolPermission(ctx, userID, toolName, mode); err != nil {
		return nil, err
	}
	return &generated.MutationResult{Success: true}, nil
}

// DeleteToolPermission is the resolver for the deleteToolPermission field.
func (r *mutationResolver) DeleteToolPermission(ctx context.Context, userID string, toolName string) (*generated.MutationResult, error) {
	if r.Deps == nil {
		return &generated.MutationResult{Success: true}, nil
	}
	if err := r.Deps.DeleteToolPermission(ctx, userID, toolName); err != nil {
		return nil, err
	}
	return &generated.MutationResult{Success: true}, nil
}

// SetAllToolPermissions is the resolver for the setAllToolPermissions field.
func (r *mutationResolver) SetAllToolPermissions(ctx context.Context, userID string, mode string) (*generated.MutationResult, error) {
	if r.Deps == nil {
		return &generated.MutationResult{Success: true}, nil
	}
	if err := r.Deps.SetAllToolPermissions(ctx, userID, mode); err != nil {
		return nil, err
	}
	return &generated.MutationResult{Success: true}, nil
}

// ApprovePairing is the resolver for the approvePairing field.
func (r *mutationResolver) ApprovePairing(ctx context.Context, code string, userID *string, displayName *string) (*generated.ApprovePairingResult, error) {
	if r.Deps == nil {
		return &generated.ApprovePairingResult{}, nil
	}
	res, err := r.Deps.ApprovePairing(ctx, code, utils.PtrStr(userID), utils.PtrStr(displayName))
	if err != nil {
		return nil, err
	}
	success := res != nil
	result := &generated.ApprovePairingResult{Success: success}
	if res != nil {
		result.Pairing = mappers.PairingSnapshotToPairingInfo(res)
	}
	return result, nil
}

// DenyPairing is the resolver for the denyPairing field.
func (r *mutationResolver) DenyPairing(ctx context.Context, code string, reason *string) (*generated.DenyPairingResult, error) {
	if r.Deps == nil {
		return &generated.DenyPairingResult{Success: true}, nil
	}
	if err := r.Deps.DenyPairing(ctx, code, utils.PtrStr(reason)); err != nil {
		errStr := err.Error()
		return &generated.DenyPairingResult{Success: false, Error: &errStr}, nil
	}
	return &generated.DenyPairingResult{Success: true, Code: &code}, nil
}

// ToolPermissions is the resolver for the toolPermissions field.
func (r *queryResolver) ToolPermissions(ctx context.Context, userID string) ([]*generated.ToolPermission, error) {
	if r.Deps == nil {
		return nil, nil
	}
	list, err := r.Deps.ToolPermissions(ctx, userID)
	if err != nil {
		return nil, err
	}
	return mappers.ToolPermissionsToGenerated(list), nil
}

// McpUsers is the resolver for the mcpUsers field.
// It includes the loopback user (agent/bot) at the beginning to configure scheduled task permissions.
func (r *queryResolver) McpUsers(ctx context.Context) ([]*generated.MCPUser, error) {
	if r.Deps == nil {
		return nil, nil
	}
	list, err := r.Deps.Users(ctx)
	if err != nil {
		return nil, err
	}
	out := mappers.UsersToMcpUsers(list)
	// Prepend loopback user (agent running scheduled tasks) with agent name as display
	agentName := r.Deps.AgentName(ctx)
	if agentName == "" {
		agentName = "Bot"
	}
	loopback := &generated.MCPUser{
		ChannelID:   "loopback",
		DisplayName: &agentName,
		IsAgent:     true,
	}
	result := make([]*generated.MCPUser, 0, len(out)+1)
	result = append(result, loopback)
	result = append(result, out...)
	return result, nil
}

// PendingPairings is the resolver for the pendingPairings field.
func (r *queryResolver) PendingPairings(ctx context.Context) ([]*generated.PendingPairing, error) {
	if r.Deps == nil {
		return nil, nil
	}
	list, err := r.Deps.PendingPairings(ctx)
	if err != nil {
		return nil, err
	}
	return mappers.PairingsToGenerated(list), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*generated.User, error) {
	if r.Deps == nil {
		return nil, nil
	}
	list, err := r.Deps.Users(ctx)
	if err != nil {
		return nil, err
	}
	return mappers.UsersToGenerated(list), nil
}
